// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnHGIhcBk5v_08nifusS-VwQqtJmdg5LE',
    appId: '1:385093943500:web:8e5403c5a79b6dacb04269',
    messagingSenderId: '385093943500',
    projectId: 'sport-33b4a',
    authDomain: 'sport-33b4a.firebaseapp.com',
    storageBucket: 'sport-33b4a.firebasestorage.app',
    measurementId: 'G-N38HSPDW6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_piDlgptbRS8NCvZOD9V5iwTs5T0gMTA',
    appId: '1:385093943500:android:1315a597ecea6084b04269',
    messagingSenderId: '385093943500',
    projectId: 'sport-33b4a',
    storageBucket: 'sport-33b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw3hMZqD7zIalqjeX5b8LKlz4YP73ONJM',
    appId: '1:385093943500:ios:4226c78b3cf39ca2b04269',
    messagingSenderId: '385093943500',
    projectId: 'sport-33b4a',
    storageBucket: 'sport-33b4a.firebasestorage.app',
    iosBundleId: 'com.example.sport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw3hMZqD7zIalqjeX5b8LKlz4YP73ONJM',
    appId: '1:385093943500:ios:4226c78b3cf39ca2b04269',
    messagingSenderId: '385093943500',
    projectId: 'sport-33b4a',
    storageBucket: 'sport-33b4a.firebasestorage.app',
    iosBundleId: 'com.example.sport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnHGIhcBk5v_08nifusS-VwQqtJmdg5LE',
    appId: '1:385093943500:web:c7a6024c3e6f5ef4b04269',
    messagingSenderId: '385093943500',
    projectId: 'sport-33b4a',
    authDomain: 'sport-33b4a.firebaseapp.com',
    storageBucket: 'sport-33b4a.firebasestorage.app',
    measurementId: 'G-6R9NZ1KW4G',
  );
}
