import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'services/auth_service.dart';
import 'screens/leaderboard_page.dart';
import 'screens/upcoming_matches_page.dart';
import 'screens/admin_matches_page.dart';

// Generated by running `flutterfire configure` in your project root —
// see the "Set up Firebase" step. This file does not exist yet.
import 'firebase_options.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const EthioFightApp());
}
 
class EthioFightApp extends StatelessWidget {
  const EthioFightApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EthioFight',
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      home: const AuthGate(),
    );
  }
}

/// Watches Firebase auth state and shows either the login screen or the
/// signed-in home shell. None of the uploaded files included a login UI,
/// so this is new.
class AuthGate extends StatelessWidget {
  const AuthGate({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final authService = AuthService();
    return StreamBuilder<User?>(
      stream: authService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        final user = snapshot.data;
        if (user == null) {
          return LoginPage(authService: authService);
        }
        return HomeShell(userId: user.uid, authService: authService);
      },
    );
  }
}

class LoginPage extends StatefulWidget {
  final AuthService authService;
  const LoginPage({Key? key, required this.authService}) : super(key: key);

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _nameController = TextEditingController();
  bool _isRegisterMode = false;
  bool _isSubmitting = false;

  Future<void> _submit() async {
    setState(() => _isSubmitting = true);
    final result = _isRegisterMode
        ? await widget.authService.register(
            email: _emailController.text,
            password: _passwordController.text,
            displayName: _nameController.text,
          )
        : await widget.authService.login(
            email: _emailController.text,
            password: _passwordController.text,
          );
    if (!mounted) return;
    setState(() => _isSubmitting = false);
    if (!result.success) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(result.message)));
    }
    // On success the AuthGate's StreamBuilder picks up the new auth state
    // automatically — no manual navigation needed here.
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    _nameController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(_isRegisterMode ? 'Create Account' : 'Log In')),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 400),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                if (_isRegisterMode)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: TextField(
                      controller: _nameController,
                      decoration: const InputDecoration(labelText: 'Display name', border: OutlineInputBorder()),
                    ),
                  ),
                TextField(
                  controller: _emailController,
                  keyboardType: TextInputType.emailAddress,
                  decoration: const InputDecoration(labelText: 'Email', border: OutlineInputBorder()),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: _passwordController,
                  obscureText: true,
                  decoration: const InputDecoration(labelText: 'Password', border: OutlineInputBorder()),
                ),
                const SizedBox(height: 20),
                SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: _isSubmitting ? null : _submit,
                    child: _isSubmitting
                        ? const SizedBox(
                            width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
                        : Text(_isRegisterMode ? 'Register' : 'Log In'),
                  ),
                ),
                TextButton(
                  onPressed: () => setState(() => _isRegisterMode = !_isRegisterMode),
                  child: Text(_isRegisterMode
                      ? 'Already have an account? Log in'
                      : "Don't have an account? Register"),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

/// Signed-in home: bottom-nav between the two player-facing pages you
/// already have, plus a menu entry into the admin section. In production,
/// gate the admin entry behind a real role check (e.g. a custom claim or
/// an `isAdmin` field checked server-side) rather than showing it to everyone.
class HomeShell extends StatefulWidget {
  final String userId;
  final AuthService authService;
  const HomeShell({Key? key, required this.userId, required this.authService}) : super(key: key);

  @override
  State<HomeShell> createState() => _HomeShellState();
}

class _HomeShellState extends State<HomeShell> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    final pages = [
      UpcomingMatchesPage(userId: widget.userId),
      LeaderboardPage(currentUserId: widget.userId),
    ];

    return Scaffold(
      appBar: AppBar(
        title: const Text('EthioFight'),
        actions: [
          IconButton(
            icon: const Icon(Icons.admin_panel_settings_outlined),
            tooltip: 'Admin',
            onPressed: () => Navigator.of(context).push(
              MaterialPageRoute(builder: (_) => const AdminMatchesPage()),
            ),
          ),
          IconButton(
            icon: const Icon(Icons.logout),
            tooltip: 'Log out',
            onPressed: widget.authService.logout,
          ),
        ],
      ),
      body: pages[_index],
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index,
        onDestinationSelected: (i) => setState(() => _index = i),
        destinations: const [
          NavigationDestination(icon: Icon(Icons.sports_mma), label: 'Matches'),
          NavigationDestination(icon: Icon(Icons.leaderboard), label: 'Leaderboard'),
        ],
      ),
    );
  }
}